from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetCompleteView, PasswordResetConfirmView
from django.urls import path
from django.urls import reverse_lazy

from .views import (
    chatbot_register_page,
    chatbot_login_page,
    chatbot_forgot_password_page,
    chatbot_logout,
    favicon,
    forgot_password_user,
    home_view,
    linkedin_oauth_callback,
    linkedin_oauth_start,
    linkedin_userinfo_api,
    login_chatbot_user,
    register_chatbot_user,
    scrape_linkedin_view,
    user_details_view,
    admin_create_user,
    admin_update_user,
    admin_delete_user,
    admin_toggle_status,
    admin_login_activities,
    linkedin_assistant_view,
    api_scrape_linkedin,
    api_scraped_profiles_list,
    api_delete_scraped_profile,
    api_scraped_profile_detail,
    api_update_linkedin_config,
    admin_scraped_profile_detail,
    admin_delete_scraped_profile,
)


urlpatterns = [
    path("", chatbot_register_page, name="chatbot_register"),
    path("login/", chatbot_login_page, name="chatbot_login"),
    path("forgot-password/", chatbot_forgot_password_page, name="chatbot_forgot_password"),
    path("home/", home_view, name="home"),
    path("logout/", chatbot_logout, name="chatbot_logout"),
    path("user-details/", user_details_view, name="user_details"),
    path("favicon.ico", favicon, name="favicon"),
    path("api/register/", register_chatbot_user, name="register_chatbot_user"),
    path("api/login/", login_chatbot_user, name="login_chatbot_user"),
    path("api/forgot-password/", forgot_password_user, name="forgot_password_user"),
    path("api/linkedin-scrape/", scrape_linkedin_view, name="linkedin_scrape"),
    path("assistant/", linkedin_assistant_view, name="linkedin_assistant"),
    path("api/assistant/scrape/", api_scrape_linkedin, name="api_scrape_linkedin"),
    path("api/assistant/profiles/", api_scraped_profiles_list, name="api_scraped_profiles_list"),
    path("api/assistant/profiles/<int:profile_id>/delete/", api_delete_scraped_profile, name="api_delete_scraped_profile"),
    path("api/assistant/profiles/<int:profile_id>/detail/", api_scraped_profile_detail, name="api_scraped_profile_detail"),
    path("auth/linkedin/", linkedin_oauth_start, name="linkedin_oauth_start"),
    path("auth/linkedin/callback/", linkedin_oauth_callback, name="linkedin_oauth_callback"),
    path("auth/linkedin/userinfo/", linkedin_userinfo_api, name="linkedin_userinfo_api"),
    path("api/admin/users/create/", admin_create_user, name="admin_create_user"),
    path("api/admin/users/<int:user_id>/update/", admin_update_user, name="admin_update_user"),
    path("api/admin/users/<int:user_id>/delete/", admin_delete_user, name="admin_delete_user"),
    path("api/admin/users/<int:user_id>/toggle-status/", admin_toggle_status, name="admin_toggle_status"),
    path("api/admin/users/<int:user_id>/login-activities/", admin_login_activities, name="admin_login_activities"),
    path("api/admin/config/update/", api_update_linkedin_config, name="api_update_linkedin_config"),
    path("api/admin/scraped-profiles/<int:profile_id>/detail/", admin_scraped_profile_detail, name="admin_scraped_profile_detail"),
    path("api/admin/scraped-profiles/<int:profile_id>/delete/", admin_delete_scraped_profile, name="admin_delete_scraped_profile"),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url=reverse_lazy("password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]
