# Generated by Django 5.0.14 on 2026-06-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdetails",
            name="profile_picture_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
