# Generated by Django 5.0.14 on 2026-06-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_scrapedprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkedInConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "li_at_cookie",
                    models.TextField(
                        blank=True, help_text="LinkedIn li_at cookie value"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LinkedIn Configuration",
                "verbose_name_plural": "LinkedIn Configuration",
            },
        ),
    ]
