# Generated by Django 5.0.14 on 2026-06-23 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_linkedinconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_url", models.URLField(blank=True, max_length=1000)),
                ("profile_url", models.URLField(max_length=500)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("headline", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("last_activity_date", models.CharField(blank=True, max_length=100)),
                ("posts_count", models.IntegerField(default=0)),
                ("comments_count", models.IntegerField(default=0)),
                ("reposts_count", models.IntegerField(default=0)),
                (
                    "activity_score",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Moderately Active", "Moderately Active"),
                            ("Inactive", "Inactive"),
                        ],
                        default="Inactive",
                        max_length=50,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Activity",
                "verbose_name_plural": "Lead Activities",
                "ordering": ["-created_at"],
            },
        ),
    ]
